name: Bump dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out the repository
        uses: actions/checkout@v4

      - name: Install dependency updates
        run: |
          npx npm-check-updates -u
          npm install
          npm update web-features

      - name: Commit dependency changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Bump deps" --allow-empty
          git push origin main
